<!DOCTYPE html>
<html>
<head>
<title> <h1><center><span class="header-section-number"> 1. </span> Vectores </h1></center></title>
</head>
<body>

</body>
</html>



<h2><span class="header-section-number"> 3.1 </span> Introducción </h2>

En esta lección revisamos el concepto de vector. Desde el punto de vista del aprendizaje de máquina. Entendemos un vector como un contenedor de  *n* datos, cada uno de los cuales se identifica genéricamente mediante un índice. Por ejemplo supongamos que $w$ es un vector de tamaño tres. Este vector se representa genéricamente como 

$$
\begin{equation}
w = (w_1,w_2, w_3).
\end{equation}
$$

En estadística es usual escribir los vectores el columna. En este caso $w$ se escribe como


$$
\begin{equation}
w = \begin{pmatrix} w_1\\ w_2 \\ w_3\end{pmatrix}.
\end{equation}
$$


El tipo de valores que puede contener un vector debe ser de la misma clase por convención. Por ejemplo, si $w$ es un vector de números reales, entonces *z=(3.2, 1.5, -7.2,0.0)* es un vector real de tamaño cuatro. Matemáticamente se dice el vector *z* tiene dimensión cuatro. En otras palabras, la dimension matemática de un vector es su tamaño.

El contenido y tipo de datos de un vector depende del contexto en que se está utilizando. Supongamos que se trata de construir una máquina de aprendizaje que idenfique digitos escritos a mano. Lo que se acostumbra a hacer es digitalizar las imágenes correspondientes. 

Vamos a suponer que se obtienen imágenes en escala de grises. Esto siginifica que cada punto de la imagen digitalizada es representada internamente en el computador mediante un byte. Esto siginifica que es posible representar 256 tonos de grises, con valores enteros entre 0 (blanco) hasta 255 (negro).

Un conjunto con estas características muy utilizado en el entrenamiento de máquinas de apredizaje es la base de datos MNIST (Modified National Institute of Standards and Technology database), la cual está disponible libremente en diferentes sitios de internet, así como también desde los lenguajes de programación usados en el aprendizaje de máquinas. 

   
    
La base de datos está disponible libremente en <a href="http://yann.lecun.com/exdb/mnist/">MNIST database</a>, gracias a Yann Lecun, Corina Cortes y Christopher Burger. En distintos sitios de Internet pueden encontrarse los archivos en formato csv.

La siguiente imagen tomada de Wikipedia muestra algunas de la imágenes de esta base de datos.

<img src="/files/Deep_Learning_AI_Course/Images/MnistExamples.png" alt="Simply Easy Learning" width="400" height="200">


Para el procesamiento de las imágenes, los datos son organizados en un vector (también llamado arreglo), colocando una fila a continuación de la otra. Se obtiene entonces que cada imagen es representada por un vector binario de tamaño 784 = 28  x 28. En *NumPy* el vector $w =(1,2,3)$ se pued crear como:

In [11]:
import numpy as np

w = np.array([1,2,3])
print(w)
print(w.shape)

[1 2 3]
(3,)


El vector columna se puede crear así:

In [12]:
w = np.array([[1],[2],[3]])
print(w)
print(w.shape)

[[1]
 [2]
 [3]]
(3, 1)


<h2><span class="header-section-number"> 3.2 </span> Aritmética básica de vectores numéricos</h2>
    
Mientras no se diga lo contrario, asumiremos que los vectores que usaremos tienen el mismo tamaño. Por facilidad, en las definciones usaremos vectores de tamaño $n=3$. En realidad el tamaños de los vectores puede ser cualquier número entero $n$ y las definciones se generalizan de forma obvia.

Supongamos que $a= (a_1,a_2,a_3)$ y $b=(b_1,b_2,b_3)$ son dos vectores. La suma entre $a$ Y $b$ es un vector $c$ definido por

$$
c = a+b = (a_1+b_1, a_2+b_2,a_3+b_3)
$$

En Python escribimos

In [13]:
a = np.array([1,2,3])
b = np.array([7,8,9])
c = a + b
print(c)

[ 8 10 12]


Similarmente la diferencia  de vectors $a-b$ es definida por

$$
c = a-b = (a_1-b_1, a_2-b_2,a_3-b_3)
$$

In [14]:
a = np.array([1,2,3])
b = np.array([7,8,9])
c = a - b
print(c)

[-6 -6 -6]


El producto de Hadamard, o producto elemento by elemento entre dos vectores se donota $a \odot b$ y se define como

$$
c = a\odot b = (a_1*b_1, a_2*b_2,a_3*b_3).
$$

En Pyton el producto de Hadamard se implementa simplemente usando el operador de multiplicación (*). Veamos


In [15]:
a = np.array([1,2,3])
b = np.array([7,8,9])
c = a * b
print(c)

[ 7 16 27]


La división entre vectores no es uan operación formalmente definida. En ocasiones sin embargo se requiere dividir los elementos de un vector entre los elementos de otro, elemento a elemento. Esta operación se implementa en Python simplemente usando el operador división (/)

In [16]:
a = np.array([1,2,3])
b = np.array([7,8,9])
c = a / b
print(c)

[0.14285714 0.25       0.33333333]


<h2><span class="header-section-number"> 3.2 </span> Producto escalar de vectores</h2>
